### ISSUE TITLE
Imported comments appear as comments made by the importing user

### ISSUE THREAD

**Issue by jawaad-ahmad** [gamecat69/wunderlist-to-trello#3]
Comments that are imported appear to come directly from the user running the import; there is no information captured from the original Wunderlist item indicating who wrote the original comment.

**Comment by gamecat69** [comment]
Hi Jawaad, thanks for the input.

I looked into this one. It appears the Trello API does not allow a user to be provided as text input when creating a comment. The only input that can be provided is the text and auth credentials.
More info in the Trello developer documentation [here](https://developers.trello.com/reference#cardsidactionsidactioncomments).

I suppose it would be theoretically possible to maintain Trello credentials for several users, then maintain a mapping between Wunderlist users and Trello credentials. This would allow comments to be created using different Trello credentials, which would cause a different user to appear next to the comment.  However, this is not something I want to undertake as it would add too much additional complexity. Feel free to fork this repo and kick this off though if it is important to you.

Another possible solution would be to extract the comments->author->name/email data from Wunderlist, then add this to the comment text when a Trello comment is created. I have added code to main.py for this. Are you able to test this?

**Comment by gamecat69** [comment]
The Wunderlist API only publishes id, name and avatar in the comment->author section. Updated the code to show the author name for each comment. Closing Issue.

**Comment by jawaad-ahmad** [comment]
Agreed the mapping isn't worth it, not to mention all the Wunderlist users in an item's comments might not necessarily be analogous Trello users anyway.

I agree with your idea of incorporating at least the comment author's name into the Trello card.

Regarding testing, I won't re-run this just yet; I have a suspicion I'll need to re-run in a couple weeks. If this is still observed at that time, I'll ask to get this reopened at that point. Thanks.
