### ISSUE TITLE
Duplicate list items are imported only once

### ISSUE THREAD

**Issue by jawaad-ahmad** [gamecat69/wunderlist-to-trello#5]
Observed when importing a Wunderlist list containing list items that at least have identical titles. (Didn't observe whether or not it matters if the Description is the same, but assuming it doesn't matter.)

If importing a list that contains multiple items with the same text (again possibly just headline text) for the list item, only a single card is put in the Trello list for all the instances.

**Comment by gamecat69** [comment]
This is a feature request and not an issue :)

Actually, the Trello API will not allow multiple cards to be created using the same name - it returns "Error 2". To implement this feature request, you would need to provide a method to uniquely name each Trello card as it was created, or (A simpler option), rename the Wunderlist item before running this code.

Closing this issue and updating the README.
